name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-1:
    uses: "Weetbix/actions-test-3/.github/workflows/reusable.yml@$GITHUB_SHA"
  test-job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo in main flow
        shell: bash