name: Test

on:
  push:
    branches:
      - main

jobs:
  generate-trigger-reason:
    name: Generate the trigger reason
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      reason: ${{ steps.reason.outputs.value }}
    steps:

      # The commit message are multiline. Use a regex to split out
      # just the first line, and the PR number into regex groups.
      - name: Parse commit message
        uses: actions-ecosystem/action-regex-match@v2
        id: parse-commit
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^(.*) \((\#\d*)\)'

      # Use the regex above to create a trigger reason that links back to the
      # api-definitions repository. For example:
      # "commit message (#100)" expands into:
      # "commit message Rebilly/api-definitions#100"
      - name: Create trigger reason
        id: reason
        run: echo '::set-output name=value::${{steps.parse-commit.outputs.group1}} Rebilly/api-definitions${{steps.parse-commit.outputs.group2}}'


  test-1:
    name: test 1
    runs-on: ubuntu-latest
    needs: generate-trigger-reason
    steps:

      - name: test
        run: echo test 1 ${{needs.generate-trigger-reason.outputs.reason}}

  test-2:
    name: test 2
    runs-on: ubuntu-latest
    needs: generate-trigger-reason
    steps:

      - name: test
        run: echo test 2 ${{needs.generate-trigger-reason.outputs.reason}}